-   repo: https://github.com/pre-commit/mirrors-isort
    sha: 'v4.3.4'
    hooks:
    -   id: isort

-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      args: [--line-length=120, --safe]
      language_version: python3.6

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.1-1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: mypy --ignore-missing-imports learning/
        language: system
        types: [python]
